language: rust

rust:
  - stable
  - nightly

script:
  # Start by running all the tests.
  - find . -type d -maxdepth 1 -name "day*" -print -exec sh -c "cd {} && cargo test" \;
  # Then run the programs.
  - find . -type d -maxdepth 1 -name "day*" -print -exec sh -c "cd {} && cargo run" \;
