language: rust

rust:
  - stable
  - nightly

script:
  # Start by running all the tests.
  - find . -type d -name "day*" -print -exec cd {}; cargo test \;
  # Then run the programs.
  - find . -type d -name "day*" -print -exec cd {}; cargo run \;
